# Generated by Django 5.0.6 on 2024-06-20 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userprofile",
            old_name="gender_id",
            new_name="gender",
        ),
    ]
