# Generated by Django 5.0.6 on 2024-06-20 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RegionalGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "region_name",
                    models.CharField(max_length=50, verbose_name="Region Name"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UniversityBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "branch_name",
                    models.CharField(max_length=50, verbose_name="University Branch"),
                ),
                (
                    "regional_group",
                    models.ForeignKey(
                        max_length=50,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colleges.regionalgroup",
                        verbose_name="Regional Group",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "course_name",
                    models.CharField(max_length=200, verbose_name="Course"),
                ),
                (
                    "branches",
                    models.ManyToManyField(
                        related_name="courses", to="colleges.universitybranch"
                    ),
                ),
            ],
        ),
    ]
