# Generated by Django 5.0.6 on 2024-06-20 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="universitybranch",
            name="regional_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="colleges.regionalgroup",
                verbose_name="Regional Group",
            ),
        ),
    ]
