# Generated by Django 5.0.6 on 2024-06-21 10:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("colleges", "0002_alter_universitybranch_regional_group"),
    ]

    operations = [
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Department Name"),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="course",
            old_name="course_name",
            new_name="title",
        ),
        migrations.RenameField(
            model_name="regionalgroup",
            old_name="region_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="universitybranch",
            old_name="branch_name",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="course",
            name="branches",
        ),
        migrations.AlterField(
            model_name="universitybranch",
            name="regional_group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="branches",
                to="colleges.regionalgroup",
                verbose_name="Regional Group",
            ),
        ),
    ]
